### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by hogthrob**
Minor changes, most notably the moving of the DataObjects[] to its own file, see commit message for background. Be aware to use dataObjectsCount in place where the number of dataObjects in the array is required (instead of the sizeof/sizeof calculation).

Other change fixes a minor warning and the too long charger state names for the OLED display.

### CODE REVIEW

**Comment by martinjaeger** [comment]
Agree that it's not ideal to define dataObjects array in the header file. But does it also increase code size if it is declared static? Or would the linker keep only one instance per binary? (I'm not an expert here... thanks for pointing at this issue)

**Comment by hogthrob** [comment]
It does increase the binary size in some cases: 
A "static" declared object is created in each compilation unit (each .cpp is a compilation unit in this project) separately and if used in said compilation unit (read from or written to) will consume memory. The gcc linker is smart enough not to include a static object if the static object is not required in a compilation unit without mentioning it. For a static non-const object, it will generate a warning in this case (and not include it either). So if a static const object is used in 2 different comilation units, it will consume twice as much space (if it is comes from the "same" header).  This is the whole point of the static keyword if used like this. 
 
sizeof() does not count as "use" since this is calculated during compilation time, BTW.
 
Because of this, in this actual case, no memory was freed by the refactoring. Same (luckily) applies to the adc_channel[] array, it is just used in a single unit, so no actual duplication. Still, potential cause of nasty issues and easy to fix before wasting time on debugging such code (been there, didn't like it).

**Comment by martinjaeger** [comment]
Ok, pushed lots of changes to "development" branch. Please have a look. Unfortunately, it is in a single commit, as I was doing the changes in a separate (private) repository for a different project step by step.

Major changes:
- Support for different boards improved. Planning is to use an upcoming board with STM32L0 for very low stand-by power consumption.
- ThingSet protocol put into lib/ dir. Next step: Make separate repository with better documentation for ThingSet library.
- Unit tests for ThingSet library included (native test environment currently fails to compile, have to fix again)
- CAN support now broken because I was working on ThingSet via LoRa. output_can.cpp etc. have to be reworked and adjusted to most recent ThingSet spec.
- DC/DC control part completely rewritten to support buck and boost mode with small configuration changes. I'm currently working on a DC nanogrid test setup using this charge controller. See also this documentation: http://libre.solar/docs/dcdc_control

Sorry for partly bad code structure. Didn't yet have the time to clean up everything, but wanted to let you know the current changes so that we don't do similar work twice.

Let me know how you would like to go ahead an how we can work together (maybe in separate issue).

**Comment by hogthrob** [comment]
Hi,
well, some changes indeed. Most notably the project does not build for me anymore. First issue is the that VSCode/Platformio wants to compile the mbed-USBDevice library which seems to fail on the STM32F0 targets due to lack of support. Fixed that with a lib_ignore statement for my board (which is probably a LS 0.10 (basically the 20A PCB from GitHub).
However, it does not build even with lib_ignore set correctly, then the issues are in the actual local code.
Removing config.cpp finally did the trick for me. I don't know if the stuff is working, since I don't dare to upload it to my single controller (which is connected to some real batteries) without understanding how to configured the battery characteristics properly now. 

To be honest: The "C"-fication is something I am not a fan of even after only looking briefly at it. You throw away proper type checking of function calls, lots of typedefs, you can no longer use constructors, ... 
Of course, everything can be done some way or the other in C too. But one of the reasons I picked this project was that it was written in C++. The other, by the way, was the use of PlatformIO which I wanted to understand a little better. Of course all this neside my interest in having a MPPT controller with proper hardware and open source firmware, and I liked the 20A board.

Having said this: As I don't want and are not able to invest too much time into this project, please do whatever you see as the best path for this project.  

So I think, best for me would be you go ahead and stabilize the code and I'll check back when you achieved this and see what is left to do for me (there will be something, I am sure). I'd appreciate if you would change your mind about C++ (but of course, I don't know you background and your experiences, maybe C is the better choice for you and the rest of the world).

**Pull request merged**
